"""remove separate salt field

Revision ID: b81d063ed2da
Revises: 8dfd28001137
Create Date: 2024-11-10 17:29:10.616870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b81d063ed2da'
down_revision: Union[str, None] = '8dfd28001137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
